version: '3'
services:
  transaction_importer:
    image: transaction_importer
    build: .
    container_name: transaction_importer
    ports:
      - "5010:5010"
    env_file:
      - .env
    restart: unless-stopped
    networks:
      - transaction_importer_net
      - db_net

  mysql:
    image: mysql
    container_name: transaction_importer_db
    ports:
      - "3306:3306"
    restart: unless-stopped
    command: --default-authentication-plugin=mysql_native_password
    volumes:
      - ./docker/mysql/:/docker-entrypoint-initdb.d/
    environment:
      # This is hard coded because Grafana needs it in order to connect.
      # Don't do this in production.
      MYSQL_ROOT_PASSWORD: example
      MYSQL_DATABASE: finance_dashboards_example
    networks:
      - db_net

  grafana:
    container_name: grafana
    image: grafana/grafana:latest
    restart: unless-stopped
    user: "1000"
    ports:
      - "3000:3000"
    volumes:
      - type: bind
        source: ./docker/grafana/dashboard.yml
        target: /etc/grafana/provisioning/dashboards/main.yaml
      - type: bind
        source: ./docker/grafana/datasource.yml
        target: /etc/grafana/provisioning/datasources/main.yaml
      - ./docker/grafana/dashboards/:/var/lib/grafana/dashboards/
    environment:
      GF_SECURITY_ADMIN_USER: "${GRAFANA_USERNAME}"
      GF_SECURITY_ADMIN_PASSWORD: "${GRAFANA_PASSWORD}"
      GF_INSTALL_PLUGINS: "grafana-clock-panel,natel-discrete-panel,grafana-piechart-panel"
      GF_PATHS_LOGS: "/logs"
      GF_LOG_MODE: "console file"
    networks:
      - db_net
      - transaction_importer_net

networks:
  transaction_importer_net:
    external: false
  db_net:
    external: false
