INSERT INTO finance_dashboards_example.finance_categories (id, name, parent_category) VALUES (1, 'Auto & Transport', null);
INSERT INTO finance_dashboards_example.finance_categories (id, name, parent_category) VALUES (2, 'Auto Insurance', 1);
INSERT INTO finance_dashboards_example.finance_categories (id, name, parent_category) VALUES (3, 'Auto Payment', 1);
INSERT INTO finance_dashboards_example.finance_categories (id, name, parent_category) VALUES (4, 'Gas & Fuel', 1);
INSERT INTO finance_dashboards_example.finance_categories (id, name, parent_category) VALUES (5, 'Parking', 1);
INSERT INTO finance_dashboards_example.finance_categories (id, name, parent_category) VALUES (6, 'Public Transportation', 1);
INSERT INTO finance_dashboards_example.finance_categories (id, name, parent_category) VALUES (7, 'Ride Share', 1);
INSERT INTO finance_dashboards_example.finance_categories (id, name, parent_category) VALUES (8, 'Service & Parts', 1);
INSERT INTO finance_dashboards_example.finance_categories (id, name, parent_category) VALUES (9, 'Tickets & Fines', 1);
INSERT INTO finance_dashboards_example.finance_categories (id, name, parent_category) VALUES (10, 'Bills & Utilities', null);
INSERT INTO finance_dashboards_example.finance_categories (id, name, parent_category) VALUES (11, 'Home Phone', 10);
INSERT INTO finance_dashboards_example.finance_categories (id, name, parent_category) VALUES (12, 'Internet', 10);
INSERT INTO finance_dashboards_example.finance_categories (id, name, parent_category) VALUES (13, 'Mobile Phone', 10);
INSERT INTO finance_dashboards_example.finance_categories (id, name, parent_category) VALUES (14, 'Television', 10);
INSERT INTO finance_dashboards_example.finance_categories (id, name, parent_category) VALUES (15, 'Utilities', 10);
INSERT INTO finance_dashboards_example.finance_categories (id, name, parent_category) VALUES (16, 'Business Services', null);
INSERT INTO finance_dashboards_example.finance_categories (id, name, parent_category) VALUES (17, 'Advertising', 16);
INSERT INTO finance_dashboards_example.finance_categories (id, name, parent_category) VALUES (18, 'Legal', 16);
INSERT INTO finance_dashboards_example.finance_categories (id, name, parent_category) VALUES (19, 'Office Supplies', 16);
INSERT INTO finance_dashboards_example.finance_categories (id, name, parent_category) VALUES (20, 'Printing', 16);
INSERT INTO finance_dashboards_example.finance_categories (id, name, parent_category) VALUES (21, 'Shipping', 16);
INSERT INTO finance_dashboards_example.finance_categories (id, name, parent_category) VALUES (22, 'Education', null);
INSERT INTO finance_dashboards_example.finance_categories (id, name, parent_category) VALUES (23, 'Books & Supplies', 22);
INSERT INTO finance_dashboards_example.finance_categories (id, name, parent_category) VALUES (24, 'Student Loan', 22);
INSERT INTO finance_dashboards_example.finance_categories (id, name, parent_category) VALUES (25, 'Tuition', 22);
INSERT INTO finance_dashboards_example.finance_categories (id, name, parent_category) VALUES (26, 'Entertainment', null);
INSERT INTO finance_dashboards_example.finance_categories (id, name, parent_category) VALUES (27, 'Amusement', 26);
INSERT INTO finance_dashboards_example.finance_categories (id, name, parent_category) VALUES (28, 'Arts', 26);
INSERT INTO finance_dashboards_example.finance_categories (id, name, parent_category) VALUES (29, 'Movies & DVDs', 26);
INSERT INTO finance_dashboards_example.finance_categories (id, name, parent_category) VALUES (30, 'Music', 26);
INSERT INTO finance_dashboards_example.finance_categories (id, name, parent_category) VALUES (31, 'Newspapers & Magazines', 26);
INSERT INTO finance_dashboards_example.finance_categories (id, name, parent_category) VALUES (32, 'Fees & Charges', null);
INSERT INTO finance_dashboards_example.finance_categories (id, name, parent_category) VALUES (33, 'ATM Fee', 32);
INSERT INTO finance_dashboards_example.finance_categories (id, name, parent_category) VALUES (34, 'Bank Fee', 32);
INSERT INTO finance_dashboards_example.finance_categories (id, name, parent_category) VALUES (35, 'Finance Charge', 32);
INSERT INTO finance_dashboards_example.finance_categories (id, name, parent_category) VALUES (36, 'Late Fee', 32);
INSERT INTO finance_dashboards_example.finance_categories (id, name, parent_category) VALUES (37, 'Service Fee', 32);
INSERT INTO finance_dashboards_example.finance_categories (id, name, parent_category) VALUES (38, 'Trade Commissions', 32);
INSERT INTO finance_dashboards_example.finance_categories (id, name, parent_category) VALUES (39, 'Financial', null);
INSERT INTO finance_dashboards_example.finance_categories (id, name, parent_category) VALUES (40, 'Financial Advisor', 39);
INSERT INTO finance_dashboards_example.finance_categories (id, name, parent_category) VALUES (41, 'Life Insurance', 39);
INSERT INTO finance_dashboards_example.finance_categories (id, name, parent_category) VALUES (42, 'Food & Dining', null);
INSERT INTO finance_dashboards_example.finance_categories (id, name, parent_category) VALUES (43, 'Alcohol & Bars', 42);
INSERT INTO finance_dashboards_example.finance_categories (id, name, parent_category) VALUES (44, 'Coffee Shops', 42);
INSERT INTO finance_dashboards_example.finance_categories (id, name, parent_category) VALUES (45, 'Fast Food', 42);
INSERT INTO finance_dashboards_example.finance_categories (id, name, parent_category) VALUES (46, 'Food Delivery', 42);
INSERT INTO finance_dashboards_example.finance_categories (id, name, parent_category) VALUES (47, 'Groceries', 42);
INSERT INTO finance_dashboards_example.finance_categories (id, name, parent_category) VALUES (48, 'Hello Fresh', 42);
INSERT INTO finance_dashboards_example.finance_categories (id, name, parent_category) VALUES (49, 'Restaurants', 42);
INSERT INTO finance_dashboards_example.finance_categories (id, name, parent_category) VALUES (50, 'Gifts & Donations', null);
INSERT INTO finance_dashboards_example.finance_categories (id, name, parent_category) VALUES (51, 'Charity', 50);
INSERT INTO finance_dashboards_example.finance_categories (id, name, parent_category) VALUES (52, 'Gift', 50);
INSERT INTO finance_dashboards_example.finance_categories (id, name, parent_category) VALUES (53, 'Health & Fitness', null);
INSERT INTO finance_dashboards_example.finance_categories (id, name, parent_category) VALUES (54, 'Dentist', 53);
INSERT INTO finance_dashboards_example.finance_categories (id, name, parent_category) VALUES (55, 'Doctor', 53);
INSERT INTO finance_dashboards_example.finance_categories (id, name, parent_category) VALUES (56, 'Eyecare', 53);
INSERT INTO finance_dashboards_example.finance_categories (id, name, parent_category) VALUES (57, 'Gym', 53);
INSERT INTO finance_dashboards_example.finance_categories (id, name, parent_category) VALUES (58, 'Health Insurance', 53);
INSERT INTO finance_dashboards_example.finance_categories (id, name, parent_category) VALUES (59, 'Pharmacy', 53);
INSERT INTO finance_dashboards_example.finance_categories (id, name, parent_category) VALUES (60, 'Sports', 53);
INSERT INTO finance_dashboards_example.finance_categories (id, name, parent_category) VALUES (61, 'Hide from Budgets & Trends', null);
INSERT INTO finance_dashboards_example.finance_categories (id, name, parent_category) VALUES (62, 'Home', null);
INSERT INTO finance_dashboards_example.finance_categories (id, name, parent_category) VALUES (63, 'Furnishings', 62);
INSERT INTO finance_dashboards_example.finance_categories (id, name, parent_category) VALUES (64, 'Home Improvement', 62);
INSERT INTO finance_dashboards_example.finance_categories (id, name, parent_category) VALUES (65, 'Home Insurance', 62);
INSERT INTO finance_dashboards_example.finance_categories (id, name, parent_category) VALUES (66, 'Home Owners Assoc', 62);
INSERT INTO finance_dashboards_example.finance_categories (id, name, parent_category) VALUES (67, 'Home Services', 62);
INSERT INTO finance_dashboards_example.finance_categories (id, name, parent_category) VALUES (68, 'Home Supplies', 62);
INSERT INTO finance_dashboards_example.finance_categories (id, name, parent_category) VALUES (69, 'Lawn & Garden', 62);
INSERT INTO finance_dashboards_example.finance_categories (id, name, parent_category) VALUES (70, 'Mortgage & Rent', 62);
INSERT INTO finance_dashboards_example.finance_categories (id, name, parent_category) VALUES (71, 'Income', null);
INSERT INTO finance_dashboards_example.finance_categories (id, name, parent_category) VALUES (72, 'Bonus', 71);
INSERT INTO finance_dashboards_example.finance_categories (id, name, parent_category) VALUES (73, 'Interest Income', 71);
INSERT INTO finance_dashboards_example.finance_categories (id, name, parent_category) VALUES (74, 'Paycheck', 71);
INSERT INTO finance_dashboards_example.finance_categories (id, name, parent_category) VALUES (75, 'Reimbursement', 71);
INSERT INTO finance_dashboards_example.finance_categories (id, name, parent_category) VALUES (76, 'Rental Income', 71);
INSERT INTO finance_dashboards_example.finance_categories (id, name, parent_category) VALUES (77, 'Returned Purchase', 71);
INSERT INTO finance_dashboards_example.finance_categories (id, name, parent_category) VALUES (78, 'Tax Return', 71);
INSERT INTO finance_dashboards_example.finance_categories (id, name, parent_category) VALUES (79, 'Investments', null);
INSERT INTO finance_dashboards_example.finance_categories (id, name, parent_category) VALUES (80, 'Buy', 79);
INSERT INTO finance_dashboards_example.finance_categories (id, name, parent_category) VALUES (81, 'Deposit', 79);
INSERT INTO finance_dashboards_example.finance_categories (id, name, parent_category) VALUES (82, 'Dividend & Cap Gains', 79);
INSERT INTO finance_dashboards_example.finance_categories (id, name, parent_category) VALUES (83, 'Sell', 79);
INSERT INTO finance_dashboards_example.finance_categories (id, name, parent_category) VALUES (84, 'Withdrawal', 79);
INSERT INTO finance_dashboards_example.finance_categories (id, name, parent_category) VALUES (85, 'Kids', null);
INSERT INTO finance_dashboards_example.finance_categories (id, name, parent_category) VALUES (86, 'Allowance', 85);
INSERT INTO finance_dashboards_example.finance_categories (id, name, parent_category) VALUES (87, 'Baby Supplies', 85);
INSERT INTO finance_dashboards_example.finance_categories (id, name, parent_category) VALUES (88, 'Babysitter & Daycare', 85);
INSERT INTO finance_dashboards_example.finance_categories (id, name, parent_category) VALUES (89, 'Child Support', 85);
INSERT INTO finance_dashboards_example.finance_categories (id, name, parent_category) VALUES (90, 'College Fund', 85);
INSERT INTO finance_dashboards_example.finance_categories (id, name, parent_category) VALUES (91, 'Kids Activities', 85);
INSERT INTO finance_dashboards_example.finance_categories (id, name, parent_category) VALUES (92, 'Toys', 85);
INSERT INTO finance_dashboards_example.finance_categories (id, name, parent_category) VALUES (93, 'Loans', null);
INSERT INTO finance_dashboards_example.finance_categories (id, name, parent_category) VALUES (94, 'Loan Fees and Charges', 93);
INSERT INTO finance_dashboards_example.finance_categories (id, name, parent_category) VALUES (95, 'Loan Insurance', 93);
INSERT INTO finance_dashboards_example.finance_categories (id, name, parent_category) VALUES (96, 'Loan Interest', 93);
INSERT INTO finance_dashboards_example.finance_categories (id, name, parent_category) VALUES (97, 'Loan Payment', 93);
INSERT INTO finance_dashboards_example.finance_categories (id, name, parent_category) VALUES (98, 'Loan Principal', 93);
INSERT INTO finance_dashboards_example.finance_categories (id, name, parent_category) VALUES (99, 'Misc Expenses', null);
INSERT INTO finance_dashboards_example.finance_categories (id, name, parent_category) VALUES (100, 'Personal Care', null);
INSERT INTO finance_dashboards_example.finance_categories (id, name, parent_category) VALUES (101, 'Hair', 100);
INSERT INTO finance_dashboards_example.finance_categories (id, name, parent_category) VALUES (102, 'Laundry', 100);
INSERT INTO finance_dashboards_example.finance_categories (id, name, parent_category) VALUES (103, 'Spa & Massage', 100);
INSERT INTO finance_dashboards_example.finance_categories (id, name, parent_category) VALUES (104, 'Pets', null);
INSERT INTO finance_dashboards_example.finance_categories (id, name, parent_category) VALUES (105, 'Pet Food & Supplies', 104);
INSERT INTO finance_dashboards_example.finance_categories (id, name, parent_category) VALUES (106, 'Pet Grooming', 104);
INSERT INTO finance_dashboards_example.finance_categories (id, name, parent_category) VALUES (107, 'Veterinary', 104);
INSERT INTO finance_dashboards_example.finance_categories (id, name, parent_category) VALUES (108, 'Shopping', null);
INSERT INTO finance_dashboards_example.finance_categories (id, name, parent_category) VALUES (109, 'Books', 108);
INSERT INTO finance_dashboards_example.finance_categories (id, name, parent_category) VALUES (110, 'Clothing', 108);
INSERT INTO finance_dashboards_example.finance_categories (id, name, parent_category) VALUES (111, 'Electronics & Software', 108);
INSERT INTO finance_dashboards_example.finance_categories (id, name, parent_category) VALUES (112, 'Hobbies', 108);
INSERT INTO finance_dashboards_example.finance_categories (id, name, parent_category) VALUES (113, 'Sporting Goods', 108);
INSERT INTO finance_dashboards_example.finance_categories (id, name, parent_category) VALUES (114, 'Taxes', null);
INSERT INTO finance_dashboards_example.finance_categories (id, name, parent_category) VALUES (115, 'Federal Tax', 114);
INSERT INTO finance_dashboards_example.finance_categories (id, name, parent_category) VALUES (116, 'Local Tax', 114);
INSERT INTO finance_dashboards_example.finance_categories (id, name, parent_category) VALUES (117, 'Property Tax', 114);
INSERT INTO finance_dashboards_example.finance_categories (id, name, parent_category) VALUES (118, 'Sales Tax', 114);
INSERT INTO finance_dashboards_example.finance_categories (id, name, parent_category) VALUES (119, 'State Tax', 114);
INSERT INTO finance_dashboards_example.finance_categories (id, name, parent_category) VALUES (120, 'Transfer', null);
INSERT INTO finance_dashboards_example.finance_categories (id, name, parent_category) VALUES (121, 'Credit Card Payment', 120);
INSERT INTO finance_dashboards_example.finance_categories (id, name, parent_category) VALUES (122, 'Transfer for Cash Spending', 120);
INSERT INTO finance_dashboards_example.finance_categories (id, name, parent_category) VALUES (123, 'Travel', null);
INSERT INTO finance_dashboards_example.finance_categories (id, name, parent_category) VALUES (124, 'Air Travel', 123);
INSERT INTO finance_dashboards_example.finance_categories (id, name, parent_category) VALUES (125, 'Hotel', 123);
INSERT INTO finance_dashboards_example.finance_categories (id, name, parent_category) VALUES (126, 'Rental Car & Taxi', 123);
INSERT INTO finance_dashboards_example.finance_categories (id, name, parent_category) VALUES (127, 'Vacation', 123);
INSERT INTO finance_dashboards_example.finance_categories (id, name, parent_category) VALUES (128, 'Uncategorized', null);
INSERT INTO finance_dashboards_example.finance_categories (id, name, parent_category) VALUES (129, 'Cash & ATM', null);
INSERT INTO finance_dashboards_example.finance_categories (id, name, parent_category) VALUES (130, 'Check', null);
INSERT INTO finance_dashboards_example.finance_categories (id, name, parent_category) VALUES (131, 'Solar Loan', null);
INSERT INTO finance_dashboards_example.finance_categories (id, name, parent_category) VALUES (132, '6.00', null);
INSERT INTO finance_dashboards_example.finance_categories (id, name, parent_category) VALUES (133, '', null);
INSERT INTO finance_dashboards_example.finance_categories (id, name, parent_category) VALUES (134, 'Unknown', null);
INSERT INTO finance_dashboards_example.finance_categories (id, name, parent_category) VALUES (135, 'Dividend', null);
