{
 "title": "Financial Transactions",
 "time": { "from": "2024-02-28 00:00:00", "to": "2024-03-15 00:00:00" },
 "templating": {
  "list": [
   { "name": "DS_MYSQL", "query": "mysql" }
  ]
 },
 "panels": [
  { "title": "Finance Graphs", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Transactions",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 9, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "targets": [
    {
     "dataset": "finance_dashboards_example",
     "rawSql": "SELECT\n  date AS \"time\",\n  description,\n  transaction_type,\n  -(amount) as debit\nFROM finance_transactions\nwhere transaction_type = 'debit'\nAND $__timeFilter(date)\nORDER BY date"
    },
    {
     "dataset": "finance_dashboards_example",
     "rawSql": "SELECT\n  date AS \"time\",\n  description,\n  transaction_type,\n  amount as credit\nFROM finance_transactions\nwhere transaction_type = 'credit'\nAND $__timeFilter(date)\nORDER BY date"
    }
   ]
  },
  {
   "title": "Net Worth",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 9, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "dataset": "finance_dashboards_example",
     "rawSql": "SELECT\r\nSUM(IF(finance_accounts.type = 'mortgage' OR finance_accounts.type = 'credit card', -finance_accounts.balance, finance_accounts.balance)) \"Net Worth\"\r\nfrom finance_accounts\r\nJOIN finance_institutions ON finance_accounts.institution = finance_institutions.id"
    }
   ]
  },
  {
   "title": "Income Total",
   "type": "stat",
   "gridPos": { "h": 8, "w": 6, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "dataset": "finance_dashboards_example",
     "rawSql": "SELECT \namount as \"Amount\"\nfrom finance_transactions\nJOIN finance_categories ON finance_transactions.category = finance_categories.id\nwhere $__timeFilter(date)\nand transaction_type = 'credit'\nand (finance_categories.name = 'Income'\nor finance_categories.parent_category = 71)"
    }
   ]
  },
  {
   "title": "Spend Total",
   "type": "stat",
   "gridPos": { "h": 8, "w": 6, "x": 18, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "dataset": "finance_dashboards_example",
     "rawSql": "SELECT \namount as \"Amount\"\nfrom finance_transactions\nJOIN finance_categories ON finance_transactions.category = finance_categories.id\nwhere $__timeFilter(date)\nand transaction_type = 'debit'\nand finance_categories.name != 'Transfer'\nand finance_categories.name != 'Credit Card Payment'"
    }
   ]
  },
  {
   "title": "Net Worth Without House",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 9, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "dataset": "finance_dashboards_example",
     "rawSql": "SELECT\r\nSUM(IF(finance_accounts.type = 'mortgage' OR finance_accounts.type = 'credit card', -finance_accounts.balance, finance_accounts.balance)) \"Net Worth\"\r\nfrom finance_accounts\r\nJOIN finance_institutions ON finance_accounts.institution = finance_institutions.id\r\nwhere finance_accounts.type != 'property'"
    }
   ]
  },
  { "title": "Finance Tables", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 9 } },
  {
   "title": "Spending Log",
   "type": "table",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "targets": [
    {
     "dataset": "finance_dashboards_example",
     "rawSql": "SELECT \ndate as \"time\",\n-(amount) as \"Amount\",\ndescription as Description,\nfinance_accounts.name \"Account Name\",\nfinance_categories.name as \"Category\",\nfinance_institutions.name \"Institution\"\nfrom finance_transactions\nJOIN finance_vendors ON finance_transactions.merchant = finance_vendors.id\nJOIN finance_accounts ON finance_transactions.account = finance_accounts.id\nJOIN finance_institutions ON finance_accounts.institution = finance_institutions.id\nJOIN finance_categories ON finance_transactions.category = finance_categories.id\nwhere $__timeFilter(date)\nand transaction_type IN('debit', 'Debit')\nand finance_categories.name != 'Transfer'\norder by date desc"
    }
   ]
  },
  {
   "title": "Income Log",
   "type": "table",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "targets": [
    {
     "dataset": "finance_dashboards_example",
     "rawSql": "SELECT \ndate as \"time\",\namount as \"Amount\",\ndescription as Description,\n#finance_vendors.name as \"Merchant\",\nfinance_accounts.name \"Account Name\",\nfinance_categories.name \"Category\",\nfinance_institutions.name \"Institution\"\nfrom finance_transactions\nJOIN finance_vendors ON finance_transactions.merchant = finance_vendors.id\nJOIN finance_accounts ON finance_transactions.account = finance_accounts.id\nJOIN finance_institutions ON finance_accounts.institution = finance_institutions.id\nJOIN finance_categories ON finance_transactions.category = finance_categories.id\nwhere $__timeFilter(date)\nand (finance_categories.name = 'Income' OR finance_categories.parent_category = 71)\norder by date desc"
    }
   ]
  },
  {
   "title": "Total Spent by Category",
   "type": "table",
   "gridPos": { "h": 8, "w": 4, "x": 0, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "targets": [
    {
     "dataset": "finance_dashboards_example",
     "rawSql": "SELECT \n  finance_categories.name AS \"Category\",\n  sum(\n    if(transaction_type = 'debit', -(amount), amount)\n    ) as \"Total\"\nfrom finance_transactions\nJOIN finance_categories ON finance_transactions.category = finance_categories.id\nwhere $__timeFilter(date)\nand finance_transactions.transaction_type in ('debit', 'Debit')\nGROUP BY finance_categories.name\norder by amount desc"
    }
   ]
  },
  {
   "title": "Total Spent at Merchant",
   "type": "table",
   "gridPos": { "h": 8, "w": 8, "x": 4, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "targets": [
    {
     "dataset": "finance_dashboards_example",
     "rawSql": "SELECT \n  date as \"time\",\n  sum(\n    if(transaction_type = 'debit', -(amount), amount)\n    ) as \"Total\",\n  finance_vendors.name AS \"Merchant\"\nfrom finance_transactions\n  JOIN finance_vendors ON finance_transactions.merchant = finance_vendors.id\nwhere $__timeFilter(date)\nand finance_transactions.transaction_type in ('debit', 'Debit')\nGROUP BY finance_vendors.name\norder by amount desc"
    }
   ]
  },
  {
   "title": "Account Balances",
   "type": "table",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "targets": [
    {
     "dataset": "finance_dashboards_example",
     "rawSql": "SELECT\r\nfinance_accounts.name \"Account Name\",\r\nIF(finance_accounts.type = 'mortgage' OR finance_accounts.type = 'credit card', -finance_accounts.balance, finance_accounts.balance) \"Balance\",\r\nfinance_accounts.type \"Type\",\r\nfinance_institutions.name \"Institution\",\r\nfinance_accounts.last_updated \"Last Updated\"\r\nfrom finance_accounts\r\nJOIN finance_institutions ON finance_accounts.institution = finance_institutions.id\r\norder by finance_accounts.name "
    }
   ]
  },
  {
   "title": "Share of Category Purchases",
   "type": "piechart",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 26 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "dataset": "finance_dashboards_example",
     "rawSql": "SELECT \n  finance_categories.name AS \"Category\",\n  sum(amount) as \"Total\"\nfrom finance_transactions\nJOIN finance_categories ON finance_transactions.category = finance_categories.id\nwhere $__timeFilter(date)\nAND finance_transactions.transaction_type IN ('debit', 'Debit')\nAND finance_categories.name != 'Transfer'\nAND finance_categories.name != 'Credit Card Payment'\nGROUP BY finance_categories.name\norder by amount desc"
    }
   ]
  },
  {
   "title": "Unknown Category Purchases",
   "type": "table",
   "gridPos": { "h": 8, "w": 8, "x": 12, "y": 26 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "targets": [
    {
     "dataset": "finance_dashboards_example",
     "rawSql": "SELECT \n  date as \"time\",\n  description as \"Description\",\n  amount as \"Amount\"\nfrom finance_transactions\n  JOIN finance_categories ON finance_categories.id = finance_transactions.category\nwhere $__timeFilter(date)\nAND finance_categories.name = 'Unknown'"
    }
   ]
  }
 ]
}