{
 "title": "Finance Budgets",
 "time": { "from": "2024-02-28 00:00:00", "to": "2024-03-15 00:00:00" },
 "templating": {
  "list": [
   { "name": "DS_MYSQL", "query": "mysql" }
  ]
 },
 "panels": [
  {
   "title": "Income Budget",
   "type": "barchart",
   "gridPos": { "h": 3, "w": 11, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "targets": [
    {
     "dataset": "finance_dashboards_example",
     "rawSql": "SELECT \r\n  finance_categories.name as \"Income\",\r\n  sum(amount) as \"Total\"\r\nfrom finance_transactions\r\nJOIN finance_categories ON finance_transactions.category = finance_categories.id\r\nwhere $__timeFilter(date)\r\nand (finance_categories.name = 'Income' or parent_category = 71)"
    }
   ]
  },
  { "title": "Variable Expenses", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 3 } },
  {
   "title": "Lawn & Garden Budget",
   "type": "barchart",
   "gridPos": { "h": 3, "w": 11, "x": 0, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "targets": [
    {
     "dataset": "finance_dashboards_example",
     "rawSql": "SELECT \r\n  finance_categories.name \"Name\",\r\n  sum(amount) as \"Total\"\r\nfrom finance_transactions\r\nJOIN finance_categories ON finance_transactions.category = finance_categories.id\r\nwhere $__timeFilter(date)\r\nand (finance_categories.name = 'Lawn & Garden')"
    }
   ]
  },
  {
   "title": "Pet Food & Supplies Budget",
   "type": "barchart",
   "gridPos": { "h": 3, "w": 11, "x": 11, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "targets": [
    {
     "dataset": "finance_dashboards_example",
     "rawSql": "SELECT \r\n  finance_categories.name \"Name\",\r\n  sum(amount) as \"Total\"\r\nfrom finance_transactions\r\nJOIN finance_categories ON finance_transactions.category = finance_categories.id\r\nwhere $__timeFilter(date)\r\nand (finance_categories.name = 'Pet Food & Supplies')"
    }
   ]
  },
  {
   "title": "Restaurants Budget",
   "type": "barchart",
   "gridPos": { "h": 3, "w": 11, "x": 0, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "targets": [
    {
     "dataset": "finance_dashboards_example",
     "rawSql": "SELECT \r\n  finance_categories.name \"Name\",\r\n  sum(amount) as \"Total\"\r\nfrom finance_transactions\r\nJOIN finance_categories ON finance_transactions.category = finance_categories.id\r\nwhere $__timeFilter(date)\r\nand (finance_categories.name = 'Restaurants')"
    }
   ]
  },
  {
   "title": "Fast Food Budget",
   "type": "barchart",
   "gridPos": { "h": 3, "w": 11, "x": 11, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "targets": [
    {
     "dataset": "finance_dashboards_example",
     "rawSql": "SELECT \r\n  finance_categories.name \"Name\",\r\n  sum(amount) as \"Total\"\r\nfrom finance_transactions\r\nJOIN finance_categories ON finance_transactions.category = finance_categories.id\r\nwhere $__timeFilter(date)\r\nand (finance_categories.name = 'Fast Food')"
    }
   ]
  },
  {
   "title": "Groceries Budget",
   "type": "barchart",
   "gridPos": { "h": 3, "w": 11, "x": 0, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "targets": [
    {
     "dataset": "finance_dashboards_example",
     "rawSql": "SELECT \r\n  finance_categories.name \"Name\",\r\n  sum(amount) as \"Total\"\r\nfrom finance_transactions\r\nJOIN finance_categories ON finance_transactions.category = finance_categories.id\r\nwhere $__timeFilter(date)\r\nand (finance_categories.name = 'Groceries')"
    }
   ]
  },
  { "title": "Static Expenses", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 13 } },
  {
   "title": "Babysitter & Daycare Budget",
   "type": "barchart",
   "gridPos": { "h": 3, "w": 11, "x": 0, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "targets": [
    {
     "dataset": "finance_dashboards_example",
     "rawSql": "SELECT \r\n  finance_categories.name \"Name\",\r\n  sum(amount) as \"Total\"\r\nfrom finance_transactions\r\nJOIN finance_categories ON finance_transactions.category = finance_categories.id\r\nwhere $__timeFilter(date)\r\nand (finance_categories.name = 'Babysitter & Daycare')"
    }
   ]
  },
  {
   "title": "Mortgage Budget",
   "type": "barchart",
   "gridPos": { "h": 3, "w": 11, "x": 11, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "targets": [
    {
     "dataset": "finance_dashboards_example",
     "rawSql": "SELECT \r\n  finance_categories.name as \"Mortgage\",\r\n  sum(amount) as \"Total\"\r\nfrom finance_transactions\r\nJOIN finance_categories ON finance_transactions.category = finance_categories.id\r\nwhere $__timeFilter(date)\r\nand (finance_categories.name = 'Mortgage & Rent')"
    }
   ]
  },
  {
   "title": "Life Insurance Budget",
   "type": "barchart",
   "gridPos": { "h": 3, "w": 11, "x": 0, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "targets": [
    {
     "dataset": "finance_dashboards_example",
     "rawSql": "SELECT \r\n  finance_categories.name \"Name\",\r\n  sum(amount) as \"Total\"\r\nfrom finance_transactions\r\nJOIN finance_categories ON finance_transactions.category = finance_categories.id\r\nwhere $__timeFilter(date)\r\nand (finance_categories.name = 'Life Insurance')"
    }
   ]
  },
  {
   "title": "Auto Payment Budget",
   "type": "barchart",
   "gridPos": { "h": 3, "w": 11, "x": 11, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "targets": [
    {
     "dataset": "finance_dashboards_example",
     "rawSql": "SELECT \r\n  finance_categories.name \"Name\",\r\n  sum(amount) as \"Total\"\r\nfrom finance_transactions\r\nJOIN finance_categories ON finance_transactions.category = finance_categories.id\r\nwhere $__timeFilter(date)\r\nand (finance_categories.name = 'Auto Payment')"
    }
   ]
  },
  {
   "title": "Utilities Budget",
   "type": "barchart",
   "gridPos": { "h": 3, "w": 11, "x": 0, "y": 20 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "targets": [
    {
     "dataset": "finance_dashboards_example",
     "rawSql": "SELECT \r\n  finance_categories.name \"Name\",\r\n  sum(amount) as \"Total\"\r\nfrom finance_transactions\r\nJOIN finance_categories ON finance_transactions.category = finance_categories.id\r\nwhere $__timeFilter(date)\r\nand (finance_categories.name = 'Bills & Utilities' OR finance_categories.parent_category = 10)"
    }
   ]
  },
  {
   "title": "Home Owners Assoc Budget",
   "type": "barchart",
   "gridPos": { "h": 3, "w": 11, "x": 11, "y": 20 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "targets": [
    {
     "dataset": "finance_dashboards_example",
     "rawSql": "SELECT \r\n  finance_categories.name \"Name\",\r\n  sum(amount) as \"Total\"\r\nfrom finance_transactions\r\nJOIN finance_categories ON finance_transactions.category = finance_categories.id\r\nwhere $__timeFilter(date)\r\nand (finance_categories.name = 'Home Owners Assoc')"
    }
   ]
  },
  {
   "title": "Auto Insurance Budget",
   "type": "barchart",
   "gridPos": { "h": 3, "w": 11, "x": 0, "y": 23 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "targets": [
    {
     "dataset": "finance_dashboards_example",
     "rawSql": "SELECT \r\n  finance_categories.name \"Name\",\r\n  sum(amount) as \"Total\"\r\nfrom finance_transactions\r\nJOIN finance_categories ON finance_transactions.category = finance_categories.id\r\nwhere $__timeFilter(date)\r\nand (finance_categories.name = 'Auto Insurance')"
    }
   ]
  },
  {
   "title": "College Fund Budget",
   "type": "barchart",
   "gridPos": { "h": 3, "w": 11, "x": 11, "y": 23 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "targets": [
    {
     "dataset": "finance_dashboards_example",
     "rawSql": "SELECT \r\n  finance_categories.name \"Name\",\r\n  sum(amount) as \"Total\"\r\nfrom finance_transactions\r\nJOIN finance_categories ON finance_transactions.category = finance_categories.id\r\nwhere $__timeFilter(date)\r\nand (finance_categories.name = 'College Fund')"
    }
   ]
  },
  {
   "title": "Home Services Budget",
   "type": "barchart",
   "gridPos": { "h": 3, "w": 11, "x": 0, "y": 26 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "targets": [
    {
     "dataset": "finance_dashboards_example",
     "rawSql": "SELECT \r\n  finance_categories.name \"Name\",\r\n  sum(amount) as \"Total\"\r\nfrom finance_transactions\r\nJOIN finance_categories ON finance_transactions.category = finance_categories.id\r\nwhere $__timeFilter(date)\r\nand (finance_categories.name = 'Home Services')"
    }
   ]
  },
  {
   "title": "Internet Budget",
   "type": "barchart",
   "gridPos": { "h": 3, "w": 11, "x": 11, "y": 26 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "targets": [
    {
     "dataset": "finance_dashboards_example",
     "rawSql": "SELECT \r\n  finance_categories.name \"Name\",\r\n  sum(amount) as \"Total\"\r\nfrom finance_transactions\r\nJOIN finance_categories ON finance_transactions.category = finance_categories.id\r\nwhere $__timeFilter(date)\r\nand (finance_categories.name = 'Internet')"
    }
   ]
  }
 ]
}